name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
    
        
       # # Optional (recommended) mail server username:
       #  username: ${{secrets.MAIL_USERNAME}}
       #  # Optional (recommended) mail server password:
       #  password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: codewithwarda@gmail.com
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
